---
- hosts: localhost 
  become: no
  roles:
    - apps
  tags:
    - always 

- hosts: localhost
  become: yes
  tasks:
   - name: Install base packages
     dnf: name={{ item }} state=present
     with_items: 
      - dnf-plugins-core
      - perf
      - wireshark
      - clang
      - global
      - autojump-zsh
      - tig
      - tmux
      - gnome-tweak-tool
      - mr
      - vcsh
      - htop
      - zsh
      - terminator
      - sbt
      - happy
      - hub
      - ant
      - gradle
      - iftop
      - cmake
      - gcc-c++
      - sysstat
      - discount
      - freetype
      - python-freetype
      - freetype-devel
      - libpng-devel
      - strace
      - ruby
      - ruby-devel
      - lua
      - lua-devel
      - luajit
      - luajit-devel
      - ctags
      - python-devel
      - ngrep
      - texlive
      - texlive-smartdiagram
      - kile
      - tkinter
      - "@Development tools"
      - okular
      - python2-virtualenv
      - graphviz
      - gitk
      - powertop
      - dnf-plugins-core
      - elfutils-libelf-devel # for virtual box
      - pcp-system-tools # contains dstat
      - gtk-v4l # web cam settings
     tags:
      - yum

   - name: Install Gems
     shell: gem install {{ item }}
     with_items:
       - jekyll

- hosts: localhost
  tasks:
    - name: Install pip packages
      pip: 
        name: "{{ item }}" 
        state: present 
        extra_args: --user
      with_items:  
        - python
        - jupyter
        - matplotlib
        - plotly
        - ccm
        - blockade
      tags:
        - python

- hosts: localhost
  become: yes
  roles:
    - docker

- hosts: localhost
  become: no
  roles:
    - jabba
    - shell
    - intellij

- hosts: localhost
  become: no
  roles:
    - kubernetes 
  tags:
    - test

