---
- hosts: localhost
  sudo: yes
  tasks:
   - name: Install base packages
     yum: name={{ item }} state=present
     with_items:
      - clang
      - global
      - autojump-zsh
      - tig
      - emacs
      - tmux
      - gnome-tweak-tool
      - mr
      - vcsh
      - htop
      - zsh
      - terminator
      - ghc
      - cabal-install
      - sbt
      - java-1.8.0-openjdk-devel
      - weechat
      - happy
      - hub
      - ant
      - gradle
      - iftop
      - cmake
      - gcc-c++
      - docker-engine
      - docker-compose
      - sysstat
      - discount
      - freetype
      - python-freetype
      - freetype-devel
      - libpng-devel
      - strace
      - R
      - ruby
      - ruby-devel
      - lua
      - lua-devel
      - luajit
      - luajit-devel
      - ctags
      - python-devel
      - ngrep
      - texlive
      - texlive-smartdiagram
      - kile
      - tkinter
      - "@Development tools"
      - okular
     tags:
      - yum

   - name: Update cabal
     command: cabal update

- hosts: localhost
  sudo: no
  tasks:
   - name: Install cabal packages
     shell: cabal install {{ item }} creates=~/.cabal/packages/hackage.haskell.org/{{ item }}
     with_items:
       - mtl
       - ghc-mod
       - hasktags
       - stylish-haskell
       - hlint

   - name: Install Gems
     shell: gem install {{ item }}
     with_items:
       - jekyll

   - name: Install oh my zsh
     shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- hosts: localhost
  sudo: yes
  tasks:
    - name: Install pip packages
      pip: name={{ item }} state=present
      with_items:  
        - python
        - jupyter
        - matplotlib
        - plotly
        - ccm
      tags:
        - python

# Roles that require root
- hosts: localhost
  sudo: yes
  roles:
    - vscode
    - intellij
  tags:
    - root_user

# Roles to run as your user
- hosts: localhost
  roles:
    - brew
    - stack
    - shell
  tags:
    - not_root
