---
- hosts: localhost
  sudo: yes
  tasks:
   - name: Install base packages
     yum: name={{ item }} state=present
     with_items:
      - emacs
      - tmux
      - gnome-tweak-tool
      - mr
      - vcsh
      - htop
      - zsh
      - terminator
      - ghc
      - cabal-install
      - sbt
#      - dropbox
      - java-1.8.0-openjdk-devel
      - weechat
      - golang
      - happy
   - name: Update cabal
     command: cabal update
   - name: Install cabal packages
     command: cabal install -p {{ item }}
     with_items:
       - mtl
       - ghc-mod
       - hasktags

   - name: Install go packages
     shell: go get {{ item }} 
     args:
       executable: /usr/bin/zsh
     environment:
       GOPATH: /home/chbatey/dev/gopath
     with_items:
       - github.com/koron/maven-search
       - github.com/tools/godep
     tags:
       - golang

  - name: Install oh my zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- hosts: localhost
  roles:
    - { role: "repos", tags: [ "repos" ] }
      
