---
- hosts: localhost
  become: yes
  tasks:
   - name: Install base packages
     dnf: name={{ item }} state=present
     with_items: 
      - dnf-plugins-core
      - "@Development tools"

# TODO this is currently fedora specific
- hosts: localhost
  become: yes
  roles:
    - docker

- hosts: localhost
  become: no
  roles:
    - kubernetes # todo don't install this if RAM < 32GB and put in main

