---
- hosts: localhost
  sudo: yes
  tasks:
   - name: Install base packages
     yum: name={{ item }} state=present
     with_items:
      - perf
      - wireshark
      - clang
      - global
      - autojump-zsh
      - tig
      - emacs
      - tmux
      - gnome-tweak-tool
      - mr
      - vcsh
      - htop
      - zsh
      - terminator
      - sbt
      - java-1.8.0-openjdk-devel
      - weechat
      - happy
      - hub
      - ant
      - gradle
      - iftop
      - cmake
      - gcc-c++
      - docker-engine
      - docker-compose
      - sysstat
      - discount
      - freetype
      - python-freetype
      - freetype-devel
      - libpng-devel
      - strace
      - ruby
      - ruby-devel
      - lua
      - lua-devel
      - luajit
      - luajit-devel
      - ctags
      - python-devel
      - ngrep
      - texlive
      - texlive-smartdiagram
      - kile
      - tkinter
      - "@Development tools"
      - okular
      - python2-virtualenv
      - graphviz
      - gitk
     tags:
      - yum

   - name: Install Gems
     shell: gem install {{ item }}
     with_items:
       - jekyll

   - name: Install oh my zsh
     shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
     tags:
       - shell

- hosts: localhost
  sudo: no
  tasks:
    - name: Install pip packages
      pip: 
        name: "{{ item }}" 
        state: present 
        extra_args: --user
      with_items:  
        - python
        - jupyter
        - matplotlib
        - plotly
        - ccm
        - blockade
      tags:
        - python

# Roles that require root
- hosts: localhost
  sudo: yes
  roles:
          #- {role: "xmonad", tags: [ "xmonad" ] }
    - vscode
    - intellij
    - clion
  tags:
    - root_user

# Roles to run as your user
- hosts: localhost
  roles:
    - brew
    - stack
    - shell
  tags:
    - not_root
    - shell
