---
- hosts: localhost
  sudo: yes
  tasks:
   - name: Install base packages
     yum: name={{ item }} state=present
     with_items:
      - autojump-zsh
      - tig
      - emacs
      - tmux
      - gnome-tweak-tool
      - mr
      - vcsh
      - htop
      - zsh
      - terminator
      - ghc
      - cabal-install
      - sbt
#      - dropbox
      - java-1.8.0-openjdk-devel
      - weechat
      - golang
      - happy
      - hub
      - ant
      - gradle

   - name: Update cabal
     command: cabal update

- hosts: localhost
  sudo: no
  tasks:
   - name: Install cabal packages
     shell: cabal install {{ item }} creates=~/.cabal/packages/hackage.haskell.org/{{ item }}
     with_items:
       - mtl
       - ghc-mod
       - hasktags
       - stylish-haskell
       - hlint

   - name: Install go packages
     shell: go get {{ item }}
     args:
       executable: /usr/bin/zsh
     environment:
       GOPATH: /home/chbatey/dev/gopath
     with_items:
       - github.com/koron/maven-search
       - github.com/tools/godep
     tags:
       - golang

   - name: Install oh my zsh
     shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- hosts: localhost
  sudo: yes
  roles:
    - { role: "work", tags: [ "work" ] }

- hosts: localhost
  sudo: yes
  tasks:
    - name: Install pip packages
      pip: name=ccm
      tags:
        - python
