---
- hosts: localhost
  become: yes
  tasks:
   - name: Install base packages
     apt: name={{ item }} state=present
     with_items: 
       - build-essential
       - zsh 
       - curl
       - terminator
       - ruby 
       - gem
       - ruby-dev
       - gnome-shell-pomodoro
       - nautilus-dropbox
       - graphviz
       - virtualbox 
       - virtualbox-ext-pack
       - wireshark 
       - lshw
       - tmux
       - vcsh
       - mr 
       - gnome-tweaks
