---
- hosts: localhost
  become: yes
  tasks:
   - name: Install base packages
     apt: name={{ item }} state=present
     with_items: 
       - zsh 
       - curl
       - terminator
       - ruby 
       - gem
       - ruby-dev
       - gnome-shell-pomodoro
