- name: Create apps directory 
  file: path="{{ home_dir }}/apps" state=directory

- name: Check if intellij  exists
  stat:
    path: "{{ home_dir }}apps/idea/"
  register: intellij

- name: Download intellij
  unarchive:
    src: "https://download.jetbrains.com/idea/{{ intellij_version }}.tar.gz"
    dest: "{{ home_dir }}apps/"
    creates: "{{ home_dir}}/apps/{{ intellij_build }}/"
    remote_src: True

- name: Symlink
  file:
    src: "{{ home_dir }}apps/{{ intellij_build }}"
    dest: "{{ home_dir }}apps/idea"
    state: link


