- name: Check if brew exists 
  stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_file

- name: Install brew for linux
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
  when: brew_file.stat.exists == False

- name: Install modules
  shell: /home/linuxbrew/.linuxbrew/bin/brew install {{ item }}
  with_items:  "{{ modules }}"
