- name: Install kubectl 
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.10.0/bin/linux/amd64/kubectl
    dest: "{{ home_dir }}apps/bin/kubectl"
    mode: 500

- name: Install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/v0.30.0/minikube-linux-amd64
    dest: "{{ home_dir }}apps/bin/minikube"
    mode: 500


