- name: Check if clion exists
  stat:
    path: /opt/clion/
  register: intellij

- name: Download clion
  unarchive:
    src: https://download.jetbrains.com/cpp/CLion-2016.3.5.tar.gz
    dest: /opt/
    creates: "/opt/clion"
    remote_src: True

- name: Symlink
  file:
    src: "/opt/clion-2016.3.5"
    dest: /opt/clion
    state: link


