- name: Add docker repo
  shell:  'dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo'

- name: Update dnf package index
  dnf:
   name: docker-ce
   state: latest

- name: Start docker service
  systemd:
    state: started
    name: docker
